### ISSUE TITLE
Cannot Generate any keypairs

### ISSUE THREAD

**Issue by so0602** [ObsidianLabs/BSC-Studio#5]
I try to create keypairs (click the 'key' icon at the bottom left side), I input the key name like 'mykey' & click 'regenerate', seems that it has not any response. What can I do?

Thanks

**Comment by qftgtr** [comment]
Thanks for reporting the bug. We will fix it ASAP.

**Comment by qftgtr** [comment]
Hi @so0602, this is fixed now! Please update to v0.7.1 if you are using the desktop version, or just refresh the page for the web version.

**Comment by so0602** [comment]
I tried to use the desktop version, seems also does not work. I already refreshed my chrome.

**Comment by so0602** [comment]
I tried to log in using Safari, it shows the blank page.
After that, I signed out at chrome & log in again, I can generate keypair now.

**Comment by qftgtr** [comment]
> I tried to use the desktop version, seems also does not work. I already refreshed my chrome.

Can you make sure you are using the latest v0.7.1 of the desktop version? We just looked at the issue again and keypair creation works for v0.7.1.

**Comment by qftgtr** [comment]
> I tried to use the desktop version, seems also does not work. I already refreshed my chrome.

This is probably because of the browser cache. If you try refreshing the page without cache it should work.
